"""
ngspice backend for circuit simulation.

This module provides the interface to the ngspice simulator.
"""

"""
    check_ngspice() -> (Bool, String, String)

Check if ngspice is installed and available in PATH.

# Returns
- `is_installed::Bool`: Whether ngspice is available
- `version::String`: Version string if available
- `path::String`: Path to the executable
"""
function check_ngspice()
    try
        result = read(`ngspice --version`, String)
        lines = split(result, '\n')
        version_line = ""
        for line in lines
            if occursin("ngspice", lowercase(line))
                version_line = strip(line)
                break
            end
        end

        # Get the path to ngspice executable
        path = strip(read(`which ngspice`, String))

        return (true, version_line, path)
    catch e
        return (false, "", "")
    end
end

"""
    to_spice_netlist(comp::AbstractCircuitComponent) -> String

Generate a SPICE netlist line for a component.
Must be implemented for each component type in the component's file.
"""
function to_spice_netlist end

# Fallback for unsupported components
function to_spice_netlist(comp::AbstractCircuitComponent)::String
    "* Unknown component: $(typeof(comp))"
end

"""
    netlist_ngspice(c::Circuit) -> String

Generate a complete SPICE netlist for ngspice simulator.
"""
function netlist_ngspice(c::Circuit)
    assign_nodes!(c)

    lines = String[]
    push!(lines, "* SPICE netlist generated by CircuitSim.jl")
    push!(lines, "")

    for comp in c.components
        push!(lines, to_spice_netlist(comp))
    end

    push!(lines, "")
    push!(lines, ".end")

    return join(lines, "\n")
end

"""
    run_ngspice(c::Circuit, analysis::AbstractAnalysis; output_file::String="")

Run ngspice simulation with the given circuit and analysis.

# Arguments
- `c::Circuit`: The circuit to simulate
- `analysis::AbstractAnalysis`: Analysis type (DCAnalysis, ACAnalysis, etc.)
- `output_file::String=""`: Optional output file path. If empty, uses a temporary file.

# Returns
- `(success::Bool, output::String, netlist::String)`

# Example
```julia
success, output, netlist = run_ngspice(c, DCAnalysis())
```
"""
function run_ngspice(c::Circuit, analysis::AbstractAnalysis; output_file::String="")
    # Check if ngspice is installed
    is_installed, version, path = check_ngspice()
    if !is_installed
        error("ngspice is not installed or not found in PATH. Please install ngspice first.")
    end

    # Generate netlist
    netlist = netlist_ngspice(c)

    # Add analysis command before .end
    analysis_str = to_spice_analysis(analysis)
    lines = split(netlist, '\n')
    end_idx = findfirst(line -> strip(line) == ".end", lines)
    if end_idx !== nothing
        splice!(lines, end_idx:end_idx-1, [analysis_str])
        push!(lines, ".end")
        netlist = join(lines, '\n')
    end

    # Create temporary file for netlist
    netlist_file = tempname() * ".cir"
    write(netlist_file, netlist)

    # Determine output file
    use_temp_output = isempty(output_file)
    if use_temp_output
        output_file = tempname() * ".out"
    end

    try
        # Run ngspice in batch mode
        result = read(`ngspice -b $netlist_file -o $output_file`, String)

        # Read the output
        output = read(output_file, String)

        # Clean up temporary files
        rm(netlist_file, force=true)
        if use_temp_output
            rm(output_file, force=true)
        end

        return (true, output, netlist)
    catch e
        # Clean up on error
        rm(netlist_file, force=true)
        if use_temp_output
            rm(output_file, force=true)
        end
        return (false, "Error running ngspice: $e", netlist)
    end
end

"""
    run_ngspice(c::Circuit, analyses::Vector{<:AbstractAnalysis}; output_file::String="")

Run ngspice simulation with multiple analysis types.
"""
function run_ngspice(c::Circuit, analyses::Vector{<:AbstractAnalysis}; output_file::String="")
    # Check if ngspice is installed
    is_installed, version, path = check_ngspice()
    if !is_installed
        error("ngspice is not installed or not found in PATH. Please install ngspice first.")
    end

    # Generate netlist
    netlist = netlist_ngspice(c)

    # Add all analysis commands before .end
    lines = split(netlist, '\n')
    end_idx = findfirst(line -> strip(line) == ".end", lines)
    if end_idx !== nothing
        analysis_strs = [to_spice_analysis(a) for a in analyses]
        splice!(lines, end_idx:end_idx-1, analysis_strs)
        push!(lines, ".end")
        netlist = join(lines, '\n')
    end

    # Create temporary file for netlist
    netlist_file = tempname() * ".cir"
    write(netlist_file, netlist)

    # Determine output file
    use_temp_output = isempty(output_file)
    if use_temp_output
        output_file = tempname() * ".out"
    end

    try
        # Run ngspice in batch mode
        result = read(`ngspice -b $netlist_file -o $output_file`, String)

        # Read the output
        output = read(output_file, String)

        # Clean up temporary files
        rm(netlist_file, force=true)
        if use_temp_output
            rm(output_file, force=true)
        end

        return (true, output, netlist)
    catch e
        # Clean up on error
        rm(netlist_file, force=true)
        if use_temp_output
            rm(output_file, force=true)
        end
        return (false, "Error running ngspice: $e", netlist)
    end
end
