"""
Check if ngspice is installed and available in PATH.
Returns a tuple (is_installed::Bool, version::String, path::String)
"""
function check_ngspice()
    try
        result = read(`ngspice --version`, String)
        lines = split(result, '\n')
        version_line = ""
        for line in lines
            if occursin("ngspice", lowercase(line))
                version_line = strip(line)
                break
            end
        end

        # Get the path to ngspice executable
        path = strip(read(`which ngspice`, String))

        return (true, version_line, path)
    catch e
        return (false, "", "")
    end
end

"""
Generate SPICE netlist for ngspice simulator.
"""
function netlist_ngspice(c::Circuit)
    assign_nodes!(c)

    lines = String[]
    push!(lines, "* SPICE netlist generated by CircuitTypes.jl")
    push!(lines, "")

    for comp in c.components
        if comp isa Resistor
            push!(lines, "R$(comp.name) $(comp.n1) $(comp.n2) $(comp.value)")
        elseif comp isa Capacitor
            push!(lines, "C$(comp.name) $(comp.n1) $(comp.n2) $(comp.value)")
        elseif comp isa Inductor
            push!(lines, "L$(comp.name) $(comp.n1) $(comp.n2) $(comp.value)")
        elseif comp isa DCVoltageSource
            # SPICE format: Vname nplus nminus DC value
            push!(lines, "V$(comp.name) $(comp.nplus) $(comp.nminus) DC $(comp.dc)")
        elseif comp isa DCCurrentSource
            # SPICE format: Iname nplus nminus DC value
            # Current flows from nminus to nplus (into nplus)
            push!(lines, "I$(comp.name) $(comp.nplus) $(comp.nminus) DC $(comp.dc)")
        elseif comp isa ACVoltageSource
            # SPICE format: Vname nplus nminus DC dcval AC acmag acphase SIN(vo va freq td theta phase)
            # For transient: SIN(offset amplitude freq delay damping phase)
            # For AC analysis: AC acmag acphase
            if comp.dc != 0.0
                push!(lines, "V$(comp.name) $(comp.nplus) $(comp.nminus) DC $(comp.dc) AC $(comp.ac_mag) $(comp.ac_phase) SIN($(comp.dc) $(comp.ac_mag) $(comp.freq) 0 0 $(comp.ac_phase))")
            else
                push!(lines, "V$(comp.name) $(comp.nplus) $(comp.nminus) AC $(comp.ac_mag) $(comp.ac_phase) SIN(0 $(comp.ac_mag) $(comp.freq) 0 0 $(comp.ac_phase))")
            end
        elseif comp isa ACCurrentSource
            # SPICE format: Iname nplus nminus DC dcval AC acmag acphase SIN(vo va freq td theta phase)
            if comp.dc != 0.0
                push!(lines, "I$(comp.name) $(comp.nplus) $(comp.nminus) DC $(comp.dc) AC $(comp.ac_mag) $(comp.ac_phase) SIN($(comp.dc) $(comp.ac_mag) $(comp.freq) 0 0 $(comp.ac_phase))")
            else
                push!(lines, "I$(comp.name) $(comp.nplus) $(comp.nminus) AC $(comp.ac_mag) $(comp.ac_phase) SIN(0 $(comp.ac_mag) $(comp.freq) 0 0 $(comp.ac_phase))")
            end
        elseif comp isa Ground
            push!(lines, "* Ground $(comp.name) -> node 0")
        else
            push!(lines, "* Unknown component: $(typeof(comp))")
        end
    end

    push!(lines, "")
    push!(lines, ".end")

    return join(lines, "\n")
end

"""
Run ngspice simulation with the given circuit and analysis commands.

# Arguments
- `c::Circuit`: The circuit to simulate
- `analysis::Vector{String}`: SPICE analysis commands (e.g., [".dc V1 0 5 0.1", ".print dc v(1) v(2)"])
- `output_file::String=""`: Optional output file path. If empty, uses a temporary file.

# Returns
- `(success::Bool, output::String, netlist::String)`

# Example
```julia
success, output, netlist = run_ngspice(c, [".op", ".print dc v(1)"])
```
"""
function run_ngspice(c::Circuit, analysis::Vector{String}=String[]; output_file::String="")
    # Check if ngspice is installed
    is_installed, version, path = check_ngspice()
    if !is_installed
        error("ngspice is not installed or not found in PATH. Please install ngspice first.")
    end

    # Generate netlist
    netlist = netlist_ngspice(c)

    # Add analysis commands before .end
    if !isempty(analysis)
        lines = split(netlist, '\n')
        # Insert analysis commands before .end
        end_idx = findfirst(line -> strip(line) == ".end", lines)
        if end_idx !== nothing
            splice!(lines, end_idx:end_idx-1, analysis)
            push!(lines, ".end")
            netlist = join(lines, '\n')
        end
    end

    # Create temporary file for netlist
    netlist_file = tempname() * ".cir"
    write(netlist_file, netlist)

    # Determine output file
    use_temp_output = isempty(output_file)
    if use_temp_output
        output_file = tempname() * ".out"
    end

    try
        # Run ngspice in batch mode
        result = read(`ngspice -b $netlist_file -o $output_file`, String)

        # Read the output
        output = read(output_file, String)

        # Clean up temporary files
        rm(netlist_file, force=true)
        if use_temp_output
            rm(output_file, force=true)
        end

        return (true, output, netlist)
    catch e
        # Clean up on error
        rm(netlist_file, force=true)
        if use_temp_output
            rm(output_file, force=true)
        end
        return (false, "Error running ngspice: $e", netlist)
    end
end
