"""
Module for generating Qucs-like netlists from CircuitTypes.jl circuits.
"""
function netlist_qucs(c::Circuit)
    assign_nodes!(c)

    lines = String[]
    push!(lines, "# Qucs-like netlist generated by CircuitTypes")
    for comp in c.components
        if comp isa Resistor
            push!(lines, "R$(comp.name) $(comp.n1) $(comp.n2) $(format_value(comp.value))")
        elseif comp isa Capacitor
            push!(lines, "C$(comp.name) $(comp.n1) $(comp.n2) $(format_value(comp.value))")
        elseif comp isa Inductor
            push!(lines, "L$(comp.name) $(comp.n1) $(comp.n2) $(format_value(comp.value))")
        elseif comp isa DCVoltageSource
            push!(lines, "V$(comp.name) $(comp.nplus) $(comp.nminus) DC=$(format_value(comp.dc))")
        elseif comp isa Ground
            # Ground is implicit in node 0, but we can emit a comment line
            push!(lines, "# Ground $(comp.name) -> node 0")
        else
            push!(lines, "# Unsupported component $(typeof(comp)) (name field may be missing)")
        end
    end

    return join(lines, '\n')
end